# Generated by Django 5.2.4 on 2025-08-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportcard",
            name="term",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="reportcard",
            name="year",
            field=models.IntegerField(db_index=True),
        ),
    ]
